### ISSUE TITLE
unable to get past selecting server

### ISSUE THREAD

**Issue by khiles** [trakt-for-plex/configuration#16]
Ive installed the script on my server and linked it, after selecting the server in list i get a spinning loading icon forever and it never advances 

errors show 
`Registered interface "/api/home"
vendor.859d191d.js:20 Registered interface "/api/home/users"
vendor.859d191d.js:20 Registered interface "/api/invites"
vendor.859d191d.js:20 Registered interface "/api"
vendor.859d191d.js:20 Registered interface "/pms/:"
vendor.859d191d.js:20 Registered interface "/pms/playlists"
vendor.859d191d.js:20 Registered interface "/pms/social"
vendor.859d191d.js:20 Registered interface "/devices"
vendor.859d191d.js:20 Registered interface "/:"
vendor.859d191d.js:20 Registered interface "/pins"
vendor.859d191d.js:20 Registered interface ""
vendor.859d191d.js:20 Registered interface "/users"
vendor.859d191d.js:20 Registered interface "/:/plugins/*/messaging"
vendor.859d191d.js:20 Registered interface ""
vendor.859d191d.js:20 Exposed interface "/api/home"
vendor.859d191d.js:20 Exposed interface "/api/home/users"
vendor.859d191d.js:20 Exposed interface "/api/invites"
vendor.859d191d.js:20 Exposed interface "/api"
vendor.859d191d.js:20 Exposed interface "/pms/:"
vendor.859d191d.js:20 Exposed interface "/pms/playlists"
vendor.859d191d.js:20 Exposed interface "/pms/social"
vendor.859d191d.js:20 Exposed interface "/devices"
vendor.859d191d.js:20 Exposed interface "/:"
vendor.859d191d.js:20 Exposed interface "/pins"
vendor.859d191d.js:20 Exposed interface ""
vendor.859d191d.js:20 Exposed interface "/users"
vendor.859d191d.js:20 Exposed root method "devices"
vendor.859d191d.js:20 Exposed root method "pins"
vendor.859d191d.js:20 plex initialized
browser_wrapper.js:14 [IH] bootstraping for http://trakt-for-plex.github.io/configuration/#/connect
browser_wrapper.js:14 [IH] Refreshed
browser_wrapper.js:14 [IH] Starting extension.
browser_wrapper.js:14 [IH] Browser type: chrome
browser_wrapper.js:14 [IH] Browser version: 50.0.2661.102
browser_wrapper.js:14 [IH] Local storage works.
browser_wrapper.js:14 [IH] This is not a hotel site, skipping
browser_wrapper.js:14 [IH] Vertical priority 0 ready to go hidden
browser_wrapper.js:14 [IH] This is not a travel operator, skipping
browser_wrapper.js:14 [IH] Vertical priority 1 ready to go hidden
browser_wrapper.js:14 [IH] This is not a rental site, skipping
browser_wrapper.js:14 [IH] Vertical priority 2 ready to go hidden
http://trakt-for-plex.github.io/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
scripts.4ef01a59.js:1 authenticated
scripts.4ef01a59.js:2 [f533afd8f60edf63fb408840aba92d59f139570c] Testing 2 connections
vendor.859d191d.js:20 Exposed interface "/:/plugins/*/messaging"
vendor.859d191d.js:20 Exposed interface ""
vendor.859d191d.js:20 Exposed root method "details"
vendor.859d191d.js:20 Exposed root method "identity"
scripts.4ef01a59.js:2 [f533afd8f60edf63fb408840aba92d59f139570c] Testing connection: http://192.168.1.12:32400
scripts.4ef01a59.js:2 [f533afd8f60edf63fb408840aba92d59f139570c] Using connection: http://192.168.1.12:32400
scripts.4ef01a59.js:2 [f533afd8f60edf63fb408840aba92d59f139570c] Request "system.ping" Object
scripts.4ef01a59.js:2 Legacy response format returned
scripts.4ef01a59.js:2 [f533afd8f60edf63fb408840aba92d59f139570c] Response null
vendor.859d191d.js:19 Potentially unhandled rejection [1] TypeError: Cannot read property 'result' of null
    at http://trakt-for-plex.github.io/configuration/scripts/scripts.4ef01a59.js:2:6277
    at O (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:21907)
    at K (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:21539)
    at y.when (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:25213)
    at v.run (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:24249)
    at a._drain (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:27479)
    at drain (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:27133)
    at MutationObserver.b (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:9721)(anonymous function) @ vendor.859d191d.js:19`

**Comment by fuzeman** [comment]
```
scripts.4ef01a59.js:2 Legacy response format returned
```

Usually indicates you are using an old version of the plugin, do you have [v1.0.2.1](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.2.1) installed?

---------------------

Sorry for the late response, must of missed the email notification for this issue.
