### ISSUE TITLE
Synology sync gets ratings but skipping TV Episode watched status / date

### ISSUE THREAD

**Issue by andyalford** [trakt-for-plex/configuration#50]
Hey there, great util.  And so nearly working, but I have something setup wrong?

Sync from TRAKTV down to virgin Synology server (DSM 6.2.3-25426) Plex latest  1.19.4.2902
Files came from Windows Plex Server, but I did whole new Library scan
Ratings for TV / Movies seem to have come through well, but watched status only for Movies.
Any ideas?  Thanks!

Log file has :

2020-06-11 01:30:53,795 - plugin.sync.main                 (7f5edca6a700) :  WARNING (plugin.sync.main:177) - Exception raised in sync task: MaxRetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/last_activities (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)"))
Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 173, in run_wrapper
    self.run()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 260, in run
    'stop'
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/main.py", line 277, in _trigger
    func()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Li
[com.plexapp.plugins.trakttv.log](https://github.com/trakt-for-plex/configuration/files/4762852/com.plexapp.plugins.trakttv.log)
braries/Shared/elapsed/main.py", line 64, in inner
    return func(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/modes/full.py", line 23, in start
    self.trakt.refresh()
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/elapsed/main.py", line 64, in inner
    return func(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/core/task/state/trakt_.py", line 110, in refresh
    self.changes = list(self.changes)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt_sync/cache/main.py", line 39, in refresh
    for result in source.refresh(username):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt_sync/cache/sources/sync.py", line 41, in refresh
    activities = Trakt['sync'].last_activities(exceptions=True)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/base/__init__.py", line 20, in wrap
    return func(*args, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/interfaces/sync/__init__.py", line 33, in last_activities
    'validate_token'
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 149, in get
    return self.request('GET', path, params, data, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 107, in request
    return self.send(prepared)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/trakt/core/http.py", line 125, in send
    response = self.session.send(request, timeout=timeout)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: MaxRetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/last_activities (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)"))

**Comment by andyalford** [comment]
[com.plexapp.plugins.trakttv.log](https://github.com/trakt-for-plex/configuration/files/4762855/com.plexapp.plugins.trakttv.log)

**Comment by andyalford** [comment]
Further investigation, and I find that new TV shows & movie watches are being synced to TRAKTV, but still the old TV show watches are not synced?

Any ideas anyone, or do I have to go through the list manually?  

Is there an XML file I could manually edit to get it to sync up.

So nearly perfect !!!  (Thanks again to the developer.)

**Comment by Deus-Rex** [comment]
I believe I'm having this issue as well. I installed this for the first time in forever with the new changes to work nicely with the recent Plex movie stuff, which seems to be working well so far. New watches for both TV and Movies have updated Trakt fine, and Trakt has updated all of my Movie statuses on Plex to what they should be. Nice!

Though like you, TV Shows are still stuck as being unwatched, despite Trakt having the correct info. I'm curious what the problem could be. I've checked the logs and reports, and all of the content it claims to have missed from Plex are stuff that I don't have ripped, so it looks good on that front.
