### ISSUE TITLE
Unable to retrieve option 'api.enabled': 'APSWDatabaseWrapper' object has no attribute 'timeout' (Unknown Error)

### ISSUE THREAD

**Issue by gitgetgot** [trakt-for-plex/configuration#52]
Hi all,

I'm running a Plex-Server on Windows10 64Bit, have installed the Trakt-for-Plex Plugin via WebTools
and getting this,
<img width="494" alt="Bildschirmfoto 2020-08-15 um 14 12 20+" src="https://user-images.githubusercontent.com/974980/90312081-e6e5c280-df01-11ea-9587-b04514b022e6.png">

when I'm loggin into the Configuration and want to choose my Plex-Server:

`
2020-08-15 14:38:09,638 - root                             (55c) :  INFO (root:828) - 200 GET /video/trakt/:/prefs (127.0.0.1) 36.00ms
2020-08-15 14:38:10,661 - plex.objects.core.base           (1748) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: offlinetranscode
2020-08-15 14:38:10,661 - plex.objects.core.base           (1748) :  WARNING (plex.objects.core.base:156) - [Detail] Omitted attribute: pushnotifications
2020-08-15 14:38:40,986 - plex_activity.sources.s_logging.main (1748) :  INFO (plex_activity.sources.s_logging.main:84) - Unable to read log file
2020-08-15 14:38:40,993 - plugin.preferences.main          (cc4) :  WARNING (plugin.preferences.main:43) - Unable to retrieve option 'api.enabled': 'APSWDatabaseWrapper' object has no attribute 'timeout'
Traceback (most recent call last):
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\preferences\main.py", line 39, in get
    option = option_cls.get(account)
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\preferences\options\core\base\simple.py", line 48, in get
    'value': self._pack(self.default),
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 4106, in get_or_create
    return sq.get(), False
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2725, in get
    return clone.execute().next()
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2769, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2455, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3150, in execute_sql
    cursor = self.get_cursor()
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3116, in get_cursor
    return self.get_conn().cursor()
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3109, in get_conn
    self.connect()
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 3089, in connect
    **self.connect_kwargs)
  File "C:\Users\plexiglass\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\exception_wrappers\database\apsw\peewee.py", line 19, in _connect
    if self.timeout is not None:
AttributeError: 'APSWDatabaseWrapper' object has no attribute 'timeout'
2020-08-15 14:38:40,996 - root                             (cc4) :  INFO (root:828) - 200 GET /:/plugins/com.plexapp.plugins.trakttv/messaging/function/TWVzc2FnZUtpdDpBcGk_/Y2VyZWFsMQoxCmxpc3QKMQpzMTEKc3lzdGVtLnBpbmdyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_ (127.0.0.1) 8.00ms
`

[FULL DEBUG LOG here](https://pastebin.com/y2ndqQgp)

I have found an issue here "[Unknown Error when logging in](https://github.com/trakt-for-plex/configuration/issues/48)" and installed the VC stuff (x86), but unfortunately, no win.

I have another Plex-Server running on a Synology and one on Win7 64Bit and the plugins are running fine there and I can go to the configuration as expected.

Only the Win10 Plex-Server throws the "unknown error"

Any Ideas?

I have re-installed the Plugin manually and via WebTools already, restarted the PMS, rebooted Win10 (after and before installing the VC redistributables) and also deactivated the firewall (under W10).

**Comment by vchatela** [comment]
Exact same issue with Nvidia Shield Pro..
