### ISSUE TITLE
interval doesnt seem to be working still

### ISSUE THREAD

**Issue by saitoh183** [trakt-for-plex/configuration#8]
using the latest beta and i ent the scan interval to 15 mins to test it and it is not triggering

here is the log

http://pastebin.com/efEpEyVc

**Comment by fuzeman** [comment]
This is the relevant error:
```
ERROR (plugin.modules.scheduler.main:81) - Exception raised in job handler: 'NoneType' object has no attribute 'started_at'
Traceback (most recent call last):
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\modules\scheduler\main.py", line 79, in process_job
    return h.run(job)
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\modules\scheduler\handlers\h_sync\interval.py", line 40, in run
    if not self.check(job):
  File "P:\Data\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\modules\scheduler\handlers\h_sync\interval.py", line 20, in check
    if last_result.started_at <= job.due_at:
AttributeError: 'NoneType' object has no attribute 'started_at'
```

Looking into what is causing this now.

**Comment by fuzeman** [comment]
Could you test the possible fix on the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip))

**Comment by saitoh183** [comment]
trying it now

**Comment by saitoh183** [comment]
ok, the sync was triggered...just waiting on it to finish

**Comment by saitoh183** [comment]
all seems good thanks

**Comment by fuzeman** [comment]
Great, will include this fix in the next release *(today, or tomorrow..)*
